[2025-07-10T22:25:21.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-10T22:25:21.851+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-10T22:25:20.928836+00:00 [queued]>
[2025-07-10T22:25:21.860+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-10T22:25:20.928836+00:00 [queued]>
[2025-07-10T22:25:21.860+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-10T22:25:21.875+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): list_files_in_s3_bucket> on 2025-07-10 22:25:20.928836+00:00
[2025-07-10T22:25:21.881+0000] {standard_task_runner.py:72} INFO - Started process 7738 to run task
[2025-07-10T22:25:21.886+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'list_s3_files', 'list_files_in_s3_bucket', 'manual__2025-07-10T22:25:20.928836+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/aws.py', '--cfg-path', '/tmp/tmpzq6eop65']
[2025-07-10T22:25:21.888+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask list_files_in_s3_bucket
[2025-07-10T22:25:21.941+0000] {task_command.py:467} INFO - Running <TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-10T22:25:20.928836+00:00 [running]> on host dd8713d3b969
[2025-07-10T22:25:22.039+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='list_s3_files' AIRFLOW_CTX_TASK_ID='list_files_in_s3_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-07-10T22:25:20.928836+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-10T22:25:20.928836+00:00'
[2025-07-10T22:25:22.040+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-10T22:25:22.069+0000] {base.py:84} INFO - Retrieving connection 'aws_s3'
[2025-07-10T22:25:22.069+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2025-07-10T22:25:46.261+0000] {logging_mixin.py:190} INFO - test output
[2025-07-10T22:25:47.379+0000] {logging_mixin.py:190} INFO - +---------+-----------------+------------+
|full_name|            email|phone_number|
+---------+-----------------+------------+
|    ahmed|  ahmed@gmail.com|123-456-7890|
|   monged| monged@gmail.com|123-456-7891|
|  youssef|youssef@gmail.com|123-456-7892|
|      ali|    ali@gmail.com|123-456-7893|
|    gamal|  gamal@gmail.com|123-456-7894|
+---------+-----------------+------------+
only showing top 5 rows
[2025-07-10T22:25:47.389+0000] {base.py:84} INFO - Retrieving connection 'AWS_PostgreSQL'
[2025-07-10T22:25:53.953+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-10T22:25:54.011+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-10T22:25:54.013+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=list_s3_files, task_id=list_files_in_s3_bucket, run_id=manual__2025-07-10T22:25:20.928836+00:00, execution_date=20250710T222520, start_date=20250710T222521, end_date=20250710T222554
[2025-07-10T22:25:54.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-10T22:25:54.164+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-10T22:25:54.167+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
